// CREATE THE STUDENT LANDING PAGE AS SIMILAR TO THE ABOVE LANDING PAGE BUT THIS PAGE IS THE INTERACTIVE PAGE WITH THE USER/STUDENT SO I WANT YOU TO MAKE THIS PAGE MOST ATTRACTIVE AS THE PAGE CONTAINS A ATTRACTIVE INTRO VIDEO AND AS THE USER MAKE THE CURSOR DOWN THE SMOOTH ANIMATION TAKES PLACE AS THE NAVBAR COMES UPSIDE DOWN AND THE REST  CONTENT COMES FROM DOWN TO UP AND THAT PAGE CONTAINS A BIG DIV THAT SHOWS THE ADVERTISEMENT AND REST ADVERTISEMENT VIDEOS AND DOWN THAT IT WILL SHOW THE EVENTS DIV WHICH CONTAIN FOUR EVENTS AND AS WE CLICK ON THE ANY OF THE DIV  AND 



